### ISSUE TITLE
[Feature] Add quarantine command.

### ISSUE THREAD

**Issue by Cobreti1** [AresChat/sb0t#25]
ask Which is command to add someone quarantine

Thks Dude, **** send ddos me sad, grettings

**Comment by hollow87** [comment]
I do not know if there is a command can do it with a script or a filter.  There are commands to un-quarantine but not quarantine.  I shall add this to be implemented.

**Comment by hollow87** [comment]
It looks like quarantine was a feature that was meant to be added but never was.   There are alternative ways to accomplish this feature as such I feel that there is no need for the quarantine feature to be added to sb0t it self.  If you feel otherwise please comment on why that is until then I shall close this issue

**Comment by Cobreti1** [comment]
Hello hollow would not be for other your programmer to test it, time it takes ares, it is annoying use vpn change use cbot 2.65 and above change port 29992 and modify mock filters, it would be well to isolate those people and more people expose pornography, You as a programmer know how to isolate it .. greetings friend are well good start week

**Comment by hollow87** [comment]
Quarantine I'm not even 100% sure what it was SUPPOSED to accomplish.  Locking users in a separate vroom is better accomplished with scripting.  I can make it easier for users to submit scripts for live scripts.
