### ISSUE TITLE
js jurassic bug

### ISSUE THREAD

**Issue by adahox** [AresChat/sb0t#46]
Hi hollow,

when i try use this object in js. it  does not know _getter and _setter function. is possible use singleton pattern in sb0t script like script ahead ?? 
```
var isPrivate = (function(){
	var private;

	function _setPrivate(value) {
		private = value;
	}

	return {
		_getter : function() {
			return private;
		},

		_setter : function(value) {
			private = _setPrivate(value);
			return private;
		}
	}

})();

```

**Comment by hollow87** [comment]
sb0t uses the Jurassic javascript engine.

If this is a Jurassic bug please refer to https://github.com/paulbartrum/jurassic  if this was a bug that was fixed in a later version of Jurassic let me know and I will update Jurassic.

With that being said however, that code does not look right to me.  The current Jurassic uses ES4 and ES5 so for example this following snippet is similar to what you were trying to do

```javascript
var isPrivate = {
    _private: false,
    get private() {
        if(_private)
            return "yes";

        return "no";
    },
    set private(value) {
        _private = value;
    }
}
```
